### ISSUE TITLE
Automatické generování tabulky [users]

### ISSUE THREAD

**Issue by krausv** [fsv-dev/ldap-authenticator#4]
Implementovat funkci pro automatickou detekci a generování tabulky [users]

**Comment by krausv** [comment]
Přidána podpora pro generování tabulky [users].

Tabulka se nevytvoří, pokud již existuje. Závislost na Ldap\DbManageru je lazy

<pre>
ldap:
    server: 'ldaps://ldap.cuni.cz'
    port: 636
    dn: 'dc=cuni,dc=cz'
    skipDatabase: TRUE
    createDatabase: TRUE
</pre>

https://github.com/fsv-dev/ldap-authenticator/commit/b9ead6f5b01765109599bcbbafb637c4052c129c

**Comment by fsv-dev** [comment]
Přidáno.
