### ISSUE TITLE
Parametr skipDatabase

### ISSUE THREAD

**Issue by krausv** [fsv-dev/ldap-authenticator#5]
Rozpracovat pro více možností konfigurace:
- skipDatabase
- OnlyPrivilegedUsers

**Comment by krausv** [comment]
# RFC

Parametr přejmenovat na

``` php
$databaseOption = "";
```

Parametr by měl obsáhnout tyto hodnoty:

``` php
$databaseOptions = "skipDatabase";
$databaseOptions = "onlyPrivilegedUsers";
$databaseOptions = FALSE;
```

## skipDatabase

Vynechá se ověření vůči databázi. Ověřuje se pouze pomocí LDAP. Všichni uživatelé mají roli guest

## onlyPrivilegedUsers

Zjistí se, zda je uživatel v databázi. Pokud ano, načtou se mu oprávnění. V opačném případě dostane roli guest. Opět platí, že uživatel musí být v LDAP

## FALSE

Uživatel musí být v LDAP i v databázi. Oprávnění se načítají podle uvedených hodnot v tabulce [users]

**Comment by krausv** [comment]
Název

``` php
$databaseOptions
```

není dostatečně intuitivní. Možnosti:

``` php
$authentificateOptions
```

**Comment by fsv-dev** [comment]
Vyřešeno.
